[beef-tool] Create workflow for beef-tool executable
HWXLR8/beef-board pull request #105
Opened 2024-09-29 19:13 UTC by HWXLR8

Implements https://github.com/HWXLR8/beef-board/issues/104

@ASleepyCat Please give the generated executable a try on your machine, I only have 1 windows system to validate against.

2024-09-30 08:10 UTC, ASleepyCat requested changes
1. When I try to run the tool, I get a false positive from Windows AV, thinking it's a trojan (`Trojan:Win32/Wacatac.B!ml`). I think adding a notice would be a good idea.
2. The tool doesn't work without `avrdude/avrdude.exe` being present in the same directory as the tool. That should be added to the guide.
3. `avrdude` doesn't automatically exit out of DFU, so you should also mention to replug the board from the computer after flashing.

2024-09-30 08:10 UTC, ASleepyCat commented on .github/workflows/beef-tool.yml
> +          name: beef-tool.exe
The artifact is a zip file, so it gets named `beef-tool.exe.zip`. I would remove the `.exe` extension.

2024-09-30 08:11 UTC, ASleepyCat commented
Should we also point to QMK Toolbox as an alternative?

2024-10-01 03:13 UTC, HWXLR8 commented
>     2. The tool doesn't work without `avrdude/avrdude.exe` being present in the same directory as the tool. That should be added to the guide.

Currently experimenting with ways to embed `avrdude` into the executable.

2024-10-06 00:13 UTC, HWXLR8 commented
@ASleepyCat Addressed all comments

2024-10-06 08:08 UTC, ASleepyCat reviewed
Just a few more things I've noticed:

1. Instead of creating a new workflow, I would create a new build job inside `ci.yml` so that we don't have two pipelines running on every push ([like in this example](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-jobs-in-a-workflow)).
2. What happens if the `libusb` drivers aren't installed? Are people still going to have to clone/download this repo to install them?

2024-10-06 13:29 UTC, HWXLR8 commented
> Just a few more things I've noticed:
> 
>     1. Instead of creating a new workflow, I would create a new build job inside `ci.yml` so that we don't have two pipelines running on every push ([like in this example](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-jobs-in-a-workflow)).
Agreed.
>     2. What happens if the `libusb` drivers aren't installed? Are people still going to have to clone/download this repo to install them?
Thoughts on including the drivers with the package generated by the workflow?

2024-10-06 14:38 UTC, ASleepyCat commented
> Thoughts on including the drivers with the package generated by the workflow?

I think that's fine, if you include the `README` file as well for instructions.

2024-10-06 18:39 UTC, HWXLR8 commented
Done

2024-10-07 03:03 UTC, ASleepyCat approved these changes
lgtm

2024-10-07 03:11 UTC, merged