Enable firmware based device reset
HWXLR8/beef-board pull request #77
Opened 2024-05-18 21:48 UTC by HWXLR8

No need to press the button anymore :) Gave this special treatment within the FW since it does not really belong with the "configuration". Let me know your thoughts!

Closes  https://github.com/HWXLR8/beef-board/issues/30

2024-05-19 01:37 UTC, ASleepyCat commented
An SDVX controller only has seven buttons, so either we'd have to use a different button combo just for SDVX firmware or you'd have to change it to accommodate.

I'm also not comfortable with being able to enter into DFU potentially during gameplay, I prefer arcin's approach of only allowing it on device start up. That way we also could simplify the button combo check since we could instantly enter into DFU with an easier button combo.

2024-05-19 02:11 UTC, HWXLR8 commented
I agree that I do not want the user to accidentally enter DFU mode. How does the arcin work? Button combination on boot?

2024-05-19 02:17 UTC, ASleepyCat commented
> I agree that I do not want the user to accidentally enter DFU mode. How does the arcin work? Button combination on boot?

[Yeah, checks B1 and B2 I think (among other things)](https://github.com/kinetic-flow/arcin-infinitas/blob/63faaff19195c45b9033c1b530c3852ee4895480/bootloader/main.cpp#L255-L275).

2024-05-19 02:24 UTC, HWXLR8 commented
I like this idea. I think holding start on boot should be sufficient. Also "start" is agnostic between controllers.

2024-05-19 02:27 UTC, ASleepyCat commented
> I like this idea. I think holding start on boot should be sufficient. Also "start" is agnostic between controllers.

Only issue is that the start buttons don't map to the same pin (B8 (or B11?) on IIDX, B7 on SDVX, ??? on popn).

2024-05-19 02:29 UTC, HWXLR8 commented
shit, you're right. Any suggestions?

2024-05-19 02:35 UTC, ASleepyCat commented
Why not just copy what arcin does?

2024-05-19 02:44 UTC, HWXLR8 commented
That is certainly a possibility, but I like to put some thought into my design choices before copying what someone else has done. 

One advantage of being able to enter DFU at any time is that we can develop FW without the need to touch the USB cable at all. I don't know about you, but having to unplug and replug the cable can get pretty annoying especially when making frequent small changes.

2024-05-19 03:03 UTC, ASleepyCat commented
I don't really find it annoying having to replug the board after flashing. I'd rather do that than accidentally enter DFU tbh. You'd still have to replug anyway to get out of DFU, unless if you've found a solution for that.

We can always change it afterwards if it actually becomes too much of a hassle.

2024-05-19 03:31 UTC, HWXLR8 commented
I am working on a solution for the post-flash reset. But in the meantime I am willing to accept your suggestion. Will make modifications tmr.

2024-05-19 11:40 UTC, ASleepyCat commented
We could make always-on DFU entry a compile flag toggle, with it being default off.

2024-05-19 14:53 UTC, HWXLR8 commented
> We could make always-on DFU entry a compile flag toggle, with it being default off.

I am cool with the current behaviour. Changes implemented as requested. Thanks for the feedback!

2024-05-20 07:43 UTC, ASleepyCat requested changes

2024-05-20 07:43 UTC, ASleepyCat commented on fw/beef.cpp
> +  button_state = 0;
`button_state` should be initialised to 0 so this isn't necessary.

2024-05-20 07:43 UTC, ASleepyCat commented on fw/beef.cpp
> +      (button_state & BUTTON_2)) {
This can be simplified to `button_state == (BUTTON_1 | BUTTON_2)`, or call `is_pressed(BUTTON_1 | BUTTON_2)`.

2024-05-20 13:20 UTC, HWXLR8 commented
Made changes as requested.

2024-05-20 14:04 UTC, merged